### ISSUE TITLE
As a user, I want to limit the search results returned by a keyword search of letters to letters written in a specific date range so that I can find content pertaining to a specific time period.

### ISSUE THREAD

**Issue by blms** [ecds/beckett-search-ui#14]

**Comment by SteveMarvin** [comment]
It is very screwy when you try to type into that field
![image](https://user-images.githubusercontent.com/18423533/200648536-32bedc7a-b86e-4811-9cc2-b440de6cafcf.png)
it will only accept one number
[1:39](https://performant-software.slack.com/archives/D027JQ9P65T/p1667932743792219)
aha, actually, now that I got it to show 1000, the date in the dropdown are around that
![image](https://user-images.githubusercontent.com/18423533/200648570-73ea6a94-0223-471d-984e-1695cd7acd67.png)

**Comment by blms** [comment]
Closing per completion on Trello
